import = [
  # uncomment the flavour you want below:
  #  "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
[shell]
args = ['--login']
program = "/usr/bin/fish"

[cursor]
style = "Beam"

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font"

[window]
startup_mode = "Fullscreen"
dynamic_padding = true
decorations = "None"
opacity = 0.9

[window.padding]
x = 30
y = 30


[selection]
save_to_clipboard = true


#[window.dimensions]
#columns = 90
#lines = 25


[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
